---
vim_repo: https://github.com/vim/vim.git
required_tools:
  - libncurses-dev
  - libgnome2-dev
  - libgtk2.0-dev
  - libatk1.0-dev
  - libbonoboui2-dev
  - libcairo2-dev
  - libx11-dev
  - libxpm-dev
  - libxt-dev
  - libgnomeui-dev
  - python-dev
  - python3-dev
  - ruby-dev
  - lua5.1
  - liblua5.1-dev
  - libperl-dev
...