---
packages:
  - git
  - git-extras # A pack of handful additional commands for git
  - tig # NCurses-based text-mode interface for git
  - checkinstall # keeps track of everything installed by make install and similar
  - ack-grep # better searching tool than grep
  - silversearcher-ag # A code searching tool similar to ack, with a focus on speed
  - tmux
  - cloc # Tool to count lines of code
  - autojump
  - htop # An interactive process viewer for Unix, better than top
  - ranger # Console file manager with Vi key bindings
  - zsh
  - neovim # Vim with async plugins execution
  - rcm # Dotfiles management tool from Thoughtbot
  - direnv # Tool for autoloading environment variables when cd'ing into a folder
  - jq # Command-line JSON parser
  - tree # Tool able to show directory tree structure in the shell
  - ssh-copy-id
  - mosh # More robust and responsive replacement for SSH
  - wget
  - rename # cli tool for renaming multiple files
  - gnupg2
  - nodejs # tsuquyomi vim plugin doesn't recognize nvm
  - ruby
  - rust
  - groovy
  - python@2
  - openjdk-8-jdk
  - cmake
  - ant
  - maven
  - gradle
  - docker
  - mongodb
...
