---
- name: "Installing development library {{ item }}"
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ required_tools }}"
- name: Cloning vim repository
  git:
    repo: "{{ vim_repo }}"
    dest: ~/vim
    depth: 1
    version: v8.1.0105
- name: Compiling vim
  shell: |
    ./configure --with-features=huge \
                --enable-multibyte \
                --enable-rubyinterp=yes \
                --enable-pythoninterp=yes \ 
                --with-python-config-dir=/usr/lib/python2.7/config \ 
                --enable-python3interp=yes  \
                --with-python3-config-dir=/usr/lib/python3.5/config \
                --enable-perlinterp=yes \
                --enable-luainterp=yes \
                --enable-gui=gtk2 \
                --enable-cscope \
                --prefix=/usr/local 
    sudo checkinstall
  args:
    chdir: ~/vim
- name: Cleaning up
  file:
    path: ~/vim
    state: absent
...
