---
- name: "Installing development library {{ item }}"
  package:
    name: {{ item }}
    state: latest
  with_items:
    - libncurses-dev
    - libgnome2-dev
    - libgtk2.0-dev
    - libatk1.0-dev
    - libbonoboui2-dev
    - libcairo2-dev
    - libx11-dev
    - libxpm-dev
    - libxt-dev
    - libgnomeui-dev
    - python-dev
    - python3-dev
    - ruby-dev
    - lua5.1
    - liblua5.1-dev
    - libperl-dev
- name: Cloning vim repository
  git:
    repo: https://github.com/vim/vim.git
    dest: ~/vim
    depth: 1
    version: v8.1.0105
- name: Compiling vim
  shell: |
    ./configure --with-features=huge \
                --enable-multibyte \
                --enable-rubyinterp=yes \
                --enable-pythoninterp=yes \ 
                --with-python-config-dir=/usr/lib/python2.7/config \ 
                --enable-python3interp=yes  \
                --with-python3-config-dir=/usr/lib/python3.5/config \
                --enable-perlinterp=yes \
                --enable-luainterp=yes \
                --enable-gui=gtk2 \
                --enable-cscope \
                --prefix=/usr/local 
    sudo checkinstall
  args:
    chdir: ~/vim
- name: Cleaning up
  file:
    path: ~/vim
    state: absent
...
